"""add remnawave_uuid and subscription_url to users

Revision ID: 6ca557745136
Revises: cc1a3e59b00b
Create Date: 2026-04-21 12:29:44.710322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ca557745136'
down_revision: Union[str, None] = 'cc1a3e59b00b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('remnawave_uuid', sa.String(length=36), nullable=True))
    op.add_column('users', sa.Column('subscription_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'subscription_url')
    op.drop_column('users', 'remnawave_uuid')
    # ### end Alembic commands ###
