"""add device_limit to devices and pending_payments

Revision ID: 852024dfadfe
Revises: 6ca557745136
Create Date: 2026-04-21 14:15:33.487571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '852024dfadfe'
down_revision: Union[str, None] = '6ca557745136'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('device_limit', sa.Integer(), server_default='1', nullable=False))
    op.add_column('pending_payments', sa.Column('device_limit', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pending_payments', 'device_limit')
    op.drop_column('devices', 'device_limit')
    # ### end Alembic commands ###
