"""add_new_field

Revision ID: c843778f74d3
Revises: c59626e2a60f
Create Date: 2025-03-28 13:51:56.156468

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c843778f74d3"
down_revision: Union[str, None] = "c59626e2a60f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("referral_code", sa.String(), nullable=True))
    op.add_column("users", sa.Column("referred_by", sa.Integer(), nullable=True))
    op.add_column("users", sa.Column("balance", sa.Integer(), nullable=True))
    op.add_column("users", sa.Column("free_months", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "free_months")
    op.drop_column("users", "balance")
    op.drop_column("users", "referred_by")
    op.drop_column("users", "referral_code")
    # ### end Alembic commands ###
