"""add vpn_client_uuid to devices

Revision ID: cc1a3e59b00b
Revises: 19076f24ca2f
Create Date: 2026-04-13 08:41:34.695885

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'cc1a3e59b00b'
down_revision: str | None = '19076f24ca2f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('vpn_client_uuid', sa.String(length=36), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'vpn_client_uuid')
    # ### end Alembic commands ###
