from typing import Protocol

from src.apps.auth.domain.models import BotAuthToken, OtpCode


class AuthGateway(Protocol):
    async def save_otp(self, otp: OtpCode) -> None: ...

    async def get_otp(self, email: str, code: str) -> OtpCode | None: ...

    async def save_bot_token(self, token: BotAuthToken) -> None: ...

    async def get_bot_token(self, token: str) -> BotAuthToken | None: ...

    async def mark_otp_used(self, otp: OtpCode) -> None: ...

    async def mark_bot_token_used(self, token: BotAuthToken) -> None: ...
