from typing import Protocol

from src.apps.device.domain.models import Device


class DeviceGateway(Protocol):
    async def get_by_id(self, device_id: int) -> Device | None: ...

    async def get_by_name(self, device_name: str) -> Device | None: ...

    async def get_next_seq(self) -> int: ...

    async def save(self, device: Device) -> None: ...

    async def delete(self, device: Device) -> None: ...
